name: wink_manager
description: "Application de gestion pour WINK EXPRESS."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # --- AJOUTÉ POUR LA LOCALISATION ---
  flutter_localizations:
    sdk: flutter
  # --- FIN DE L'AJOUT ---

  # Gestion d'état
  provider: ^6.1.2 

  # Appels réseau (API)
  # Nous ajoutons DIO car votre auth_service.dart l'utilise
  dio: ^5.4.3+1 
  http: ^1.2.1 

  # Communication WebSocket pour le chat/notifications en temps réel
  web_socket_channel: ^3.0.0 # <-- AJOUTÉ pour l'écran Suivis/Chat Admin

  # Formatage (Dates, Nombres)
  intl: ^0.20.2 # <-- CORRIGÉ (était ^0.19.0)

  # Stockage local
  shared_preferences: ^2.2.3
  
  # --- NOUVEAU : AJOUT DU STOCKAGE SÉCURISÉ ---
  flutter_secure_storage: ^9.0.0
  # --- FIN DE L'AJOUT ---

  # --- AJOUTÉ POUR LES ACTIONS D'APPEL ---
  url_launcher: ^6.3.0


  # --- AJOUTÉ POUR LA BASE DE DONNÉES OFFLINE ---
  sqflite: ^2.3.3+1 # Base de données SQL locale
  path_provider: ^2.1.3 # Pour trouver le chemin de la DB
  connectivity_plus: ^6.0.3 # Pour détecter l'état du réseau

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png